# Generated by Django 4.2.5 on 2026-01-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0003_hruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
