# Generated by Django 4.2.5 on 2026-01-10 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0004_alter_department_code_alter_position_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveapplication',
            options={'ordering': ['-date_filed']},
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='number_of_days',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
