# Generated by Django 4.2.5 on 2026-01-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0005_alter_leaveapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('remaining_days', models.PositiveIntegerField(default=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='Main_App.employee')),
            ],
            options={
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
