# Generated by Django 4.2.5 on 2026-01-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0006_employeeleavebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereport',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
            preserve_default=False,
        ),
    ]
