# Generated by Django 4.2.5 on 2026-01-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0007_leavereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereport',
            name='review_comments',
            field=models.TextField(blank=True),
        ),
    ]
