# Generated by Django 4.2.5 on 2026-01-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0008_leavereport_review_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavereport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
