# Generated by Django 4.2.5 on 2026-01-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0009_leavereport_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hruser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hruser',
            name='full_name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hruser',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hruser',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='hruser',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='hruser',
            name='is_hr',
            field=models.BooleanField(default=True),
        ),
    ]
