# Generated by Django 4.2.5 on 2026-01-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0010_hruser_age_hruser_full_name_hruser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hruser',
            name='photo',
            field=models.ImageField(blank=True, default='assets/media/examplePIC.jpg', null=True, upload_to='hr_photos/'),
        ),
    ]
