# Generated by Django 4.2.5 on 2026-01-11 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main_App', '0011_hruser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hruser',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='hruser',
            name='username',
        ),
        migrations.AddField(
            model_name='hruser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
